// Generated by CoffeeScript 1.7.1
var extend, lucastswick, module;

module = function(namespace) {
  return window[namespace] = window[namespace] || {};
};

extend = function(ns, ns_string) {
  var i, parent, parts, pl;
  parts = ns_string.split(".");
  parent = ns;
  pl = void 0;
  i = void 0;
  if (parts[0] === "com") {
    parts = parts.slice(1);
  }
  pl = parts.length;
  i = 0;
  while (i < pl) {
    if (typeof parent[parts[i]] === "undefined") {
      parent[parts[i]] = {};
    }
    parent = parent[parts[i]];
    i++;
  }
  return parent;
};

module("com");

lucastswick = extend(com, "com.lucastswick");
