// Generated by CoffeeScript 1.8.0
module.exports = function(grunt) {
  grunt.initConfig({
    sass: {
      compile: {
        options: {
          style: 'expanded'
        },
        files: [
          {
            expand: true,
            cwd: 'lib/sass',
            src: ['**/*.scss'],
            dest: 'lib/css',
            ext: '.css'
          }
        ]
      }
    },
    coffee: {
      compile: {
        expand: true,
        cwd: 'js',
        src: ['*.coffee'],
        dest: 'js',
        ext: '.js',
        options: {
          bare: true,
          preserve_dirs: true
        }
      }
    },
    watch: {
      html: {
        files: ['**/*.html']
      },
      sass: {
        files: '<%= sass.compile.files[0].src %>',
        tasks: ['sass']
      },
      coffee: {
        files: '<%= coffee.compile.src %>',
        tasks: ['coffee']
      },
      options: {
        livereload: true
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-coffee');
  return grunt.loadNpmTasks('grunt-contrib-watch');
};
